<a href="https://colab.research.google.com/github/MOHITGHANGHAS1/AIML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [15]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [18]:
b= np.array([5.1,6.1,7.1,8.1])
print(b)

[5.1 6.1 7.1 8.1]


In [19]:
c = a+b
(c)

array([ 6.1,  8.1, 10.1, 12.1])

In [20]:
c.sort()

2-d Array

In [22]:
d= np.array([(1,2,3,4),(9,8,7,6)], dtype = float)

In [23]:
d

array([[1., 2., 3., 4.],
       [9., 8., 7., 6.]])

In [28]:
e= np.array([(3,7,2,6),(9,8,2,4)],float)
e

array([[3., 7., 2., 6.],
       [9., 8., 2., 4.]])

In [29]:
f= d+e
print(f)

[[ 4.  9.  5. 10.]
 [18. 16.  9. 10.]]


In [26]:
g=np.zeros((3,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:

i=np.arange(10,25,5)
i

array([10, 15, 20])

In [35]:
j=np.linspace(0,2,9)
j

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [36]:
j=np.linspace(0,2,100)
j

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

In [38]:
k=np.full((2,2),7)
k

array([[7, 7],
       [7, 7]])

In [39]:
l=np.eye(2)
l

array([[1., 0.],
       [0., 1.]])

In [42]:
n=np.random.random((2,2))
n

array([[0.60083008, 0.16238827],
       [0.31108972, 0.16060266]])